### ISSUE TITLE
Offer to maintain

### ISSUE THREAD

**Issue by philomates** [nubank/clj-github-app#3]
Hey @dryewo, sad to see you aren't in Berlin any longer but hope all is well on your end.

Thanks for this library! At Nubank we use a fork of it with several tweaks (https://github.com/dryewo/clj-github-app/pull/2 and https://github.com/dryewo/clj-github-app/issues/1).

I'm starting to look at open-sourcing some of the tools that use `clj-github-app` and part of that would require us opening up our fork of `clj-github-app`.
Given that, the fact that we have a few solid use-cases, and the fact that there hasn't been follow-up on the tweaks I mentioned, I was wondering if you'd be interested in passing this over to me and a few others at Nubank to maintain (like @rfhayashi + @jpalharini)

**Comment by dryewo** [comment]
Hello Phillip!
I'm totally for it. I'm glad to hear that this project is useful, and would be happy to pass it to over to you and the team.
What should I do to make this happen? I'm fine with moving it to another owner org, so that you can start evolving it officially.
What's the best way for us to coordinate it?

**Comment by rfhayashi** [comment]
@philomates Maybe we could just open our fork and @dryewo could point in the readme that this is where things are going on. Wdyt?

**Comment by philomates** [comment]
That sounds good too and maintains @dryewo's original contribution more clearly. One downside I can think of would be the additional hop / mental overhead to find the "current" version but I suppose a clear message on the original README would mitigate that.
I'll leave it up to @dryewo to specify which one is preferred and go from there.

**Comment by dryewo** [comment]
I'm fine with transferring it fully to `nubank` org. As long as you don't remove my commits from there, this is fine :)
I just invited @philomates as a collaborator. I don't see the admin option there, maybe it appears after he accepts.

**Comment by dryewo** [comment]
Even after accepting @philomates seems to be just a collaborator, and I don't see how I can make you an admin.
Let me try transfering the repo ownership to you completely, maybe then you can move it nubank org.

**Comment by philomates** [comment]
Transferring to my account allowed me to then transfer the project to nubank. From there I managed a release on clojars as `[nubank/clj-github-app 0.1.4]`
Thanks so much for trusting us with this @dryewo! 
@rfhayashi has some really nice clojure wrappers for creating commits, pull requests, etc that we'll probably be adding here (or maybe another lib, TBD) so the capabilities will expand further soon!
